//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASR.Net.CMS.Base.Company
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LicenseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LicenseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LicenseConsoleApplication.LicenseResource", typeof(LicenseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string Alphab {
            get {
                return ResourceManager.GetString("Alphab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_BIOS.
        /// </summary>
        internal static string BOS {
            get {
                return ResourceManager.GetString("BOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMBIOSBIOSVersion.
        /// </summary>
        internal static string BV {
            get {
                return ResourceManager.GetString("BV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLL not installed properlly..
        /// </summary>
        internal static string DllNotInstalled {
            get {
                return ResourceManager.GetString("DllNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string FACT {
            get {
                return ResourceManager.GetString("FACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentificationCode.
        /// </summary>
        internal static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniqueId.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPEnabled.
        /// </summary>
        internal static string IPE {
            get {
                return ResourceManager.GetString("IPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACAddress.
        /// </summary>
        internal static string MACA {
            get {
                return ResourceManager.GetString("MACA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxClockSpeed.
        /// </summary>
        internal static string MCS {
            get {
                return ResourceManager.GetString("MCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string MOD {
            get {
                return ResourceManager.GetString("MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string NEMO {
            get {
                return ResourceManager.GetString("NEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string NSTMO {
            get {
                return ResourceManager.GetString("NSTMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessorId.
        /// </summary>
        internal static string PID {
            get {
                return ResourceManager.GetString("PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDate.
        /// </summary>
        internal static string RD {
            get {
                return ResourceManager.GetString("RD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string SIG {
            get {
                return ResourceManager.GetString("SIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialNumber.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHeads.
        /// </summary>
        internal static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VER {
            get {
                return ResourceManager.GetString("VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_BaseBoard.
        /// </summary>
        internal static string WBB {
            get {
                return ResourceManager.GetString("WBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_DiskDrive.
        /// </summary>
        internal static string WDD {
            get {
                return ResourceManager.GetString("WDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_NetworkAdapterConfiguration.
        /// </summary>
        internal static string WNAC {
            get {
                return ResourceManager.GetString("WNAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_Processor.
        /// </summary>
        internal static string WP {
            get {
                return ResourceManager.GetString("WP", resourceCulture);
            }
        }
    }
}